id: IA3C0BEB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:34:40+00:00'
last_modified: '2022-06-07T22:40:55.015186+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG518
  title: ཚེར་མའི་ལམ་གྱི་ང་རོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    372B:
      image_group_id: I1KG528
      title: ''
      total_pages: 318
      order: 1
      base_file: 372B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
