id: P004410
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:19:09.190317
source_metadata:
  id: bdr:W1KG518
  title: ཚེར་མའི་ལམ་གྱི་ང་རོ།
  author: ''
  volumes:
    37227c6740544e78b4f2c0c1b2640f87:
      image_group_id: I1KG528
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
